export interface LogisticsQuestion {
  id: number;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  category: 'logistics' | 'china-market' | 'incoterms' | 'customs' | 'ecommerce' | 'payment';
  coins: number;
}

export const LOGISTICS_QUESTIONS: LogisticsQuestion[] = [
  // === LOGISTICS CƠ BẢN ===
  {
    id: 1,
    question: 'FOB (Free On Board) nghĩa là gì trong xuất nhập khẩu?',
    options: [
      'Người bán chịu mọi chi phí đến kho người mua',
      'Người bán giao hàng lên tàu tại cảng xuất, rủi ro chuyển sang người mua từ đó',
      'Người mua phải tự đến nhà máy lấy hàng',
      'Miễn phí vận chuyển toàn bộ',
    ],
    correct: 1,
    explanation: 'FOB = người bán chịu trách nhiệm đến khi hàng lên tàu tại cảng xuất. Sau đó mọi rủi ro và chi phí vận chuyển thuộc về người mua. Đây là điều kiện phổ biến nhất khi nhập hàng từ Trung Quốc.',
    category: 'incoterms',
    coins: 20,
  },
  {
    id: 2,
    question: 'CIF khác FOB ở điểm nào quan trọng nhất?',
    options: [
      'CIF rẻ hơn FOB',
      'CIF bao gồm cả cước vận chuyển và bảo hiểm đến cảng đích',
      'CIF chỉ dùng cho đường bộ',
      'CIF không cần chứng từ hải quan',
    ],
    correct: 1,
    explanation: 'CIF (Cost, Insurance, Freight) = FOB + cước tàu + bảo hiểm. Người bán chịu chi phí vận chuyển và bảo hiểm đến cảng đích. Tiện cho người mua nhưng thường giá cao hơn FOB.',
    category: 'incoterms',
    coins: 20,
  },
  {
    id: 3,
    question: 'EXW (Ex Works) có lợi cho bên nào nhất?',
    options: [
      'Người mua',
      'Người bán — vì chỉ cần giao hàng tại kho, không chịu vận chuyển',
      'Hãng tàu',
      'Đại lý hải quan',
    ],
    correct: 1,
    explanation: 'EXW có lợi nhất cho người bán — chỉ cần giao hàng tại kho/nhà máy. Toàn bộ chi phí vận chuyển, thông quan, bảo hiểm thuộc về người mua. Cần kinh nghiệm logistics để dùng EXW hiệu quả.',
    category: 'incoterms',
    coins: 20,
  },
  {
    id: 4,
    question: 'Bill of Lading (B/L) trong logistics là gì?',
    options: [
      'Hóa đơn bán hàng',
      'Vận đơn — chứng từ quan trọng nhất trong vận chuyển đường biển',
      'Giấy phép kinh doanh',
      'Hợp đồng bảo hiểm',
    ],
    correct: 1,
    explanation: 'B/L (Vận đơn đường biển) là "chìa khóa" để nhận hàng tại cảng đích. Nó vừa là biên nhận hàng hóa, vừa là hợp đồng vận chuyển, vừa là chứng từ sở hữu hàng. Mất B/L = rất rắc rối!',
    category: 'logistics',
    coins: 20,
  },
  {
    id: 5,
    question: 'Container 20ft (20GP) có thể chứa tối đa khoảng bao nhiêu CBM?',
    options: [
      '15 CBM',
      '28-33 CBM',
      '50 CBM',
      '67 CBM',
    ],
    correct: 1,
    explanation: '20GP chứa ~28-33 CBM (mét khối), tải trọng tối đa ~22-25 tấn. Container 40ft (40GP) gấp đôi: ~56-67 CBM. Biết capacity giúp tính toán đóng hàng tối ưu, tiết kiệm cước.',
    category: 'logistics',
    coins: 15,
  },
  {
    id: 6,
    question: 'LCL và FCL trong vận chuyển biển khác nhau thế nào?',
    options: [
      'LCL nhanh hơn FCL',
      'LCL = hàng lẻ ghép container, FCL = nguyên container riêng',
      'FCL chỉ dùng cho hàng nguy hiểm',
      'Không có sự khác biệt',
    ],
    correct: 1,
    explanation: 'FCL (Full Container Load) = thuê nguyên container, phù hợp hàng nhiều. LCL (Less than Container Load) = hàng lẻ ghép chung container với hàng khác, phù hợp lô nhỏ nhưng cước/CBM cao hơn.',
    category: 'logistics',
    coins: 15,
  },
  {
    id: 7,
    question: 'Thời gian vận chuyển đường biển từ Trung Quốc (Thượng Hải/Quảng Châu) về Việt Nam trung bình bao lâu?',
    options: [
      '1-2 ngày',
      '3-7 ngày',
      '15-20 ngày',
      '30-45 ngày',
    ],
    correct: 1,
    explanation: 'Đường biển từ TQ về VN: ~3-7 ngày (cảng chính). Cộng thêm 2-4 ngày thông quan. Nhanh hơn nhiều so với TQ đi EU/Mỹ (25-40 ngày). Đường bộ qua cửa khẩu: 2-5 ngày.',
    category: 'logistics',
    coins: 15,
  },
  // === THỊ TRƯỜNG TRUNG QUỐC ===
  {
    id: 8,
    question: '1688.com (Alibaba nội địa Trung Quốc) dùng để làm gì?',
    options: [
      'Mạng xã hội giống Facebook',
      'Nền tảng B2B mua sỉ hàng hóa từ nhà máy/xưởng Trung Quốc',
      'App gọi xe giống Grab',
      'Sàn bán lẻ cho người tiêu dùng',
    ],
    correct: 1,
    explanation: '1688.com là "chợ sỉ online" lớn nhất Trung Quốc — mua trực tiếp từ nhà máy/xưởng sản xuất với giá gốc. Giá rẻ hơn Alibaba.com (quốc tế) vì là nội địa. MOQ thường thấp hơn.',
    category: 'china-market',
    coins: 20,
  },
  {
    id: 9,
    question: 'Alibaba.com và 1688.com khác nhau cơ bản thế nào?',
    options: [
      'Cùng một nền tảng, không khác gì',
      'Alibaba.com cho khách quốc tế (tiếng Anh, USD), 1688.com cho nội địa TQ (tiếng Trung, RMB)',
      '1688 bán lẻ, Alibaba bán sỉ',
      'Alibaba miễn phí, 1688 tính phí',
    ],
    correct: 1,
    explanation: 'Alibaba.com = B2B quốc tế (giao diện tiếng Anh, giá USD, MOQ lớn). 1688.com = B2B nội địa TQ (tiếng Trung, giá RMB, MOQ nhỏ hơn, giá gốc hơn). Biết dùng 1688 sẽ có giá cạnh tranh hơn.',
    category: 'china-market',
    coins: 20,
  },
  {
    id: 10,
    question: 'Quảng Châu (Guangzhou) nổi tiếng là trung tâm giao thương gì?',
    options: [
      'Trung tâm công nghệ cao',
      'Thủ phủ hàng hóa, chợ sỉ lớn nhất thế giới với hàng vạn showroom',
      'Chỉ là thành phố du lịch',
      'Trung tâm nông nghiệp',
    ],
    correct: 1,
    explanation: 'Quảng Châu là "thủ phủ bán sỉ" thế giới — hàng ngàn chợ sỉ, showroom (đồ gia dụng, nội thất, điện tử, quần áo). Canton Fair tại đây là hội chợ XNK lớn nhất thế giới. Rất quan trọng với ngành XNK VN.',
    category: 'china-market',
    coins: 25,
  },
  {
    id: 11,
    question: 'Canton Fair (Hội chợ Quảng Châu) tổ chức mấy lần một năm?',
    options: [
      '1 lần',
      '2 lần — vào mùa Xuân (tháng 4) và mùa Thu (tháng 10)',
      '4 lần mỗi quý',
      '12 lần mỗi tháng',
    ],
    correct: 1,
    explanation: 'Canton Fair tổ chức 2 kỳ/năm: Xuân (15/4-5/5) và Thu (15/10-4/11). Mỗi kỳ chia 3 phase theo ngành hàng. Là cơ hội tuyệt vời để tìm nhà cung cấp, xem mẫu mới, đàm phán giá trực tiếp.',
    category: 'china-market',
    coins: 20,
  },
  {
    id: 12,
    question: 'Nghĩa Ô (Yiwu) nổi tiếng về mặt hàng gì?',
    options: [
      'Ô tô và xe máy',
      'Hàng tiêu dùng nhỏ, phụ kiện, đồ trang trí — "chợ nhỏ lớn nhất thế giới"',
      'Máy móc công nghiệp nặng',
      'Thực phẩm và nông sản',
    ],
    correct: 1,
    explanation: 'Nghĩa Ô (Yiwu) được mệnh danh "chợ nhỏ lớn nhất thế giới" — chuyên hàng tiêu dùng nhỏ: phụ kiện, đồ trang trí, đồ chơi, quà tặng, văn phòng phẩm. MOQ thấp, giá cực rẻ. Thương nhân VN rất hay đến đây.',
    category: 'china-market',
    coins: 20,
  },
  {
    id: 13,
    question: 'Phật Sơn (Foshan) nổi tiếng với ngành hàng nào?',
    options: [
      'Quần áo thời trang',
      'Gốm sứ, gạch men, nội thất, đồ gia dụng',
      'Điện thoại di động',
      'Thực phẩm đóng gói',
    ],
    correct: 1,
    explanation: 'Phật Sơn (Foshan) là "thủ phủ nội thất & vật liệu xây dựng" TQ — gốm sứ, gạch men, thiết bị vệ sinh, nội thất, đồ gia dụng. Rất liên quan đến sản phẩm Senliving của TBS Group!',
    category: 'china-market',
    coins: 25,
  },
  // === HẢI QUAN & THỦ TỤC ===
  {
    id: 14,
    question: 'C/O (Certificate of Origin) Form E dùng để làm gì?',
    options: [
      'Xin visa đi Trung Quốc',
      'Chứng nhận xuất xứ hàng hóa ASEAN-Trung Quốc để được hưởng thuế ưu đãi 0%',
      'Đăng ký thương hiệu',
      'Giấy phép kinh doanh',
    ],
    correct: 1,
    explanation: 'C/O Form E (ACFTA) cho phép hàng nhập từ TQ được hưởng thuế nhập khẩu ưu đãi (thường 0% hoặc rất thấp). Thiếu C/O Form E = phải đóng thuế MFN (cao hơn nhiều). Đây là chứng từ cực kỳ quan trọng!',
    category: 'customs',
    coins: 25,
  },
  {
    id: 15,
    question: 'HS Code (Harmonized System Code) dùng để làm gì?',
    options: [
      'Mã số thuế doanh nghiệp',
      'Mã phân loại hàng hóa quốc tế — xác định thuế suất và quy định nhập khẩu',
      'Mã vận đơn',
      'Mã bưu điện',
    ],
    correct: 1,
    explanation: 'HS Code là hệ thống mã hàng hóa quốc tế (6-10 chữ số). Mỗi sản phẩm có HS Code riêng, quyết định thuế suất, quy định kiểm tra, giấy phép cần thiết. Sai HS Code = rủi ro phạt và chậm hàng!',
    category: 'customs',
    coins: 20,
  },
  {
    id: 16,
    question: 'Khi nhập hàng từ Trung Quốc, cần đóng những loại thuế nào?',
    options: [
      'Chỉ thuế VAT',
      'Thuế nhập khẩu + Thuế VAT (và thuế TTĐB nếu có)',
      'Không phải đóng thuế',
      'Chỉ thuế thu nhập',
    ],
    correct: 1,
    explanation: 'Nhập hàng phải đóng: (1) Thuế nhập khẩu (tùy HS Code, có C/O Form E thì 0%), (2) Thuế VAT 8-10%, (3) Thuế TTĐB nếu là hàng đặc biệt (rượu, xe hơi...). Tính thuế đúng giúp dự trù chi phí chính xác.',
    category: 'customs',
    coins: 20,
  },
  // === THANH TOÁN ===
  {
    id: 17,
    question: 'T/T (Telegraphic Transfer) trong giao dịch quốc tế là gì?',
    options: [
      'Thanh toán bằng tiền mặt',
      'Chuyển khoản ngân hàng quốc tế — phương thức thanh toán phổ biến nhất với nhà cung cấp TQ',
      'Thanh toán qua Alipay',
      'Trả góp hàng tháng',
    ],
    correct: 1,
    explanation: 'T/T (chuyển khoản điện) là phương thức phổ biến nhất: thường đặt cọc 30% trước sản xuất, 70% trước khi xuất hàng. Nhanh, đơn giản nhưng cần tin tưởng đối tác. Với đơn lớn nên dùng thêm L/C.',
    category: 'payment',
    coins: 20,
  },
  {
    id: 18,
    question: 'L/C (Letter of Credit) bảo vệ ai trong giao dịch XNK?',
    options: [
      'Chỉ bảo vệ người bán',
      'Bảo vệ cả hai bên — ngân hàng đứng giữa đảm bảo thanh toán khi đủ chứng từ',
      'Chỉ bảo vệ hãng tàu',
      'Không bảo vệ ai',
    ],
    correct: 1,
    explanation: 'L/C (Thư tín dụng) = ngân hàng đứng giữa: người bán chắc chắn nhận tiền nếu giao hàng đúng, người mua chắc chắn nhận hàng đúng mới mất tiền. An toàn nhất cho đơn hàng lớn, nhưng phí cao và thủ tục phức tạp.',
    category: 'payment',
    coins: 25,
  },
  {
    id: 19,
    question: 'RMB (Nhân dân tệ) hiện tại khoảng bao nhiêu VNĐ? (2025-2026)',
    options: [
      '500-1,000 VNĐ',
      '3,400-3,600 VNĐ',
      '10,000-15,000 VNĐ',
      '23,000-25,000 VNĐ',
    ],
    correct: 1,
    explanation: '1 RMB ≈ 3,400-3,600 VNĐ (2025-2026). Tỷ giá dao động ảnh hưởng trực tiếp đến giá nhập hàng. Khi RMB tăng giá → hàng nhập đắt hơn. Theo dõi tỷ giá là kỹ năng quan trọng trong XNK.',
    category: 'payment',
    coins: 15,
  },
  // === THƯƠNG MẠI ĐIỆN TỬ XNK ===
  {
    id: 20,
    question: 'Pinduoduo (Temu) nổi lên nhờ chiến lược gì?',
    options: [
      'Bán hàng cao cấp',
      'Giá siêu rẻ, mua chung (group buying), nhà máy bán thẳng cho người tiêu dùng',
      'Chỉ bán sách',
      'Giao hàng bằng drone',
    ],
    correct: 1,
    explanation: 'Pinduoduo (và Temu quốc tế) phá giá bằng mô hình C2M (Consumer to Manufacturer) — nhà máy bán thẳng, cắt trung gian. Mua chung giảm giá thêm. Đã vượt JD.com thành sàn TMĐT lớn thứ 2 TQ sau Taobao.',
    category: 'ecommerce',
    coins: 20,
  },
  {
    id: 21,
    question: 'Taobao và Tmall thuộc tập đoàn nào?',
    options: [
      'Tencent',
      'Alibaba Group',
      'JD.com',
      'ByteDance',
    ],
    correct: 1,
    explanation: 'Taobao (C2C, giống Shopee) và Tmall (B2C, hàng chính hãng) đều thuộc Alibaba Group. Taobao có giá rẻ nhất nhưng cần biết tiếng Trung. Tmall yêu cầu thương hiệu đăng ký, hàng chất lượng hơn.',
    category: 'ecommerce',
    coins: 15,
  },
  {
    id: 22,
    question: 'Shein (thời trang fast-fashion TQ) thành công nhờ mô hình gì?',
    options: [
      'Bán hàng qua TV',
      'Small-batch, test-and-reorder — sản xuất lô nhỏ, test thị trường, đơn nào hot thì sản xuất thêm',
      'Chỉ bán offline',
      'Mua franchise thương hiệu phương Tây',
    ],
    correct: 1,
    explanation: 'Shein dùng mô hình "real-time fashion": sản xuất lô nhỏ 100-200 cái, đưa lên app, sản phẩm nào bán tốt thì tăng sản lượng. Mỗi ngày ra 2,000-3,000 mẫu mới! Ứng dụng data-driven manufacturing từ chuỗi cung ứng TQ.',
    category: 'ecommerce',
    coins: 20,
  },
  {
    id: 23,
    question: 'Douyin (TikTok nội địa TQ) đang thay đổi ngành XNK thế nào?',
    options: [
      'Không liên quan đến XNK',
      'Livestream bán hàng + liên kết nhà máy, giúp thương nhân VN tìm nguồn hàng qua video trực tiếp',
      'Chỉ dùng để giải trí',
      'Cấm bán hàng trên nền tảng',
    ],
    correct: 1,
    explanation: 'Douyin (TikTok TQ) là kênh bán hàng khổng lồ: livestream từ nhà máy, showroom, chợ sỉ. Thương nhân VN xem trực tiếp hàng mẫu, đặt hàng qua livestream. Doanh thu TMĐT Douyin đã vượt 300 tỷ USD/năm.',
    category: 'ecommerce',
    coins: 20,
  },
  // === LOGISTICS NÂNG CAO ===
  {
    id: 24,
    question: 'Cross-border e-commerce (CBEC) từ TQ sang VN là gì?',
    options: [
      'Bán hàng offline tại cửa hàng',
      'Thương mại điện tử xuyên biên giới — mua hàng TQ qua app/web, ship thẳng về VN',
      'Xuất khẩu VN sang TQ',
      'Bưu phẩm cá nhân',
    ],
    correct: 1,
    explanation: 'CBEC = mua hàng TQ online (Taobao, 1688, Pinduoduo), ship về VN qua đại lý vận chuyển hoặc kho trung chuyển. Phát triển mạnh nhờ chi phí logistics giảm và nhu cầu hàng TQ tại VN tăng.',
    category: 'logistics',
    coins: 20,
  },
  {
    id: 25,
    question: 'Bonded warehouse (kho ngoại quan) có lợi ích gì?',
    options: [
      'Chỉ để trưng bày hàng',
      'Lưu trữ hàng nhập chưa thông quan, chưa phải đóng thuế cho đến khi xuất kho',
      'Kho lạnh chuyên thực phẩm',
      'Kho dành riêng cho hàng xuất khẩu',
    ],
    correct: 1,
    explanation: 'Kho ngoại quan cho phép lưu hàng nhập mà chưa đóng thuế. Chỉ khi xuất kho vào nội địa mới tính thuế. Giúp tối ưu dòng tiền, phân phối hàng linh hoạt. Nhiều công ty dùng kho ngoại quan tại cửa khẩu VN-TQ.',
    category: 'logistics',
    coins: 25,
  },
  {
    id: 26,
    question: 'Cửa khẩu nào quan trọng nhất cho giao thương VN-TQ đường bộ?',
    options: [
      'Cửa khẩu Mộc Bài (Tây Ninh)',
      'Cửa khẩu Hữu Nghị / Tân Thanh (Lạng Sơn)',
      'Cửa khẩu Xa Mát (Tây Ninh)',
      'Cửa khẩu Hà Tiên (Kiên Giang)',
    ],
    correct: 1,
    explanation: 'Cửa khẩu Hữu Nghị (quốc tế) và Tân Thanh (song phương) tại Lạng Sơn là cửa ngõ chính cho giao thương VN-TQ đường bộ. Hàng ngàn xe container qua đây mỗi ngày. Cửa khẩu Móng Cái (Quảng Ninh) cũng rất quan trọng.',
    category: 'logistics',
    coins: 20,
  },
  {
    id: 27,
    question: 'Trong logistics, "lead time" (thời gian đặt hàng) từ TQ về VN thường tính thế nào?',
    options: [
      'Chỉ tính thời gian vận chuyển',
      'Thời gian sản xuất + đóng gói + vận chuyển + thông quan + giao hàng nội địa',
      'Chỉ tính thời gian sản xuất',
      'Chỉ tính thời gian thông quan',
    ],
    correct: 1,
    explanation: 'Lead time đầy đủ: Sản xuất (15-45 ngày) + Đóng gói (2-3 ngày) + Vận chuyển biển (3-7 ngày) + Thông quan (2-5 ngày) + Giao nội địa (1-3 ngày). Tổng: 25-60 ngày. Lập kế hoạch tốt = không thiếu hàng!',
    category: 'logistics',
    coins: 20,
  },
  {
    id: 28,
    question: 'MOQ (Minimum Order Quantity) trên 1688 thường thấp hơn Alibaba.com vì sao?',
    options: [
      'Vì 1688 là nền tảng mới',
      'Vì 1688 phục vụ thương nhân nội địa TQ, quen mua sỉ nhỏ và thường xuyên',
      'Vì hàng trên 1688 chất lượng kém hơn',
      'Vì 1688 bán lẻ',
    ],
    correct: 1,
    explanation: 'Thương nhân nội địa TQ quen mua sỉ nhỏ, đặt thường xuyên. Alibaba.com hướng khách quốc tế (MOQ lớn, đơn giá thấp hơn). 1688 MOQ có thể từ 1-50 cái, rất phù hợp doanh nghiệp nhỏ VN muốn test hàng.',
    category: 'china-market',
    coins: 20,
  },
  {
    id: 29,
    question: 'QC (Quality Control) khi nhập hàng TQ nên làm ở giai đoạn nào?',
    options: [
      'Chỉ kiểm tra khi hàng về VN',
      'Kiểm tra tại nhà máy TQ trước khi xuất hàng (Pre-shipment Inspection)',
      'Không cần kiểm tra',
      'Chỉ kiểm tra mẫu đầu tiên',
    ],
    correct: 1,
    explanation: 'QC tốt nhất = kiểm tra tại nhà máy TQ trước xuất hàng (PSI). Thuê công ty QC hoặc cử người sang. Phát hiện lỗi sớm = sửa ngay tại TQ, tránh tốn tiền ship hàng lỗi về VN rồi mới biết.',
    category: 'logistics',
    coins: 25,
  },
  {
    id: 30,
    question: 'Alipay và WeChat Pay phổ biến tại Trung Quốc đến mức nào?',
    options: [
      'Chỉ giới trẻ dùng',
      'Chiếm hơn 90% thanh toán — từ siêu thị đến hàng rong đều quét QR',
      'Chỉ dùng cho mua hàng online',
      'Đã bị cấm sử dụng',
    ],
    correct: 1,
    explanation: 'TQ gần như "cashless" — Alipay (Alibaba) và WeChat Pay (Tencent) chiếm 90%+ thanh toán. Từ mua cà phê, taxi, chợ rau đều quét QR. Đi TQ công tác/mua hàng cần có 1 trong 2 app này. Du khách VN giờ cũng dùng được.',
    category: 'payment',
    coins: 15,
  },
];

const CATEGORY_LABELS: Record<string, string> = {
  logistics: '🚢 Logistics & Vận chuyển',
  'china-market': '🇨🇳 Thị trường TQ',
  incoterms: '📋 Incoterms',
  customs: '🛃 Hải quan & Thuế',
  ecommerce: '🛒 TMĐT Trung Quốc',
  payment: '💳 Thanh toán quốc tế',
};

export { CATEGORY_LABELS };

export function getRandomLogisticsQuestions(count: number): LogisticsQuestion[] {
  const shuffled = [...LOGISTICS_QUESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
